version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g pnpm
  pre_build:
    commands:
      - pnpm install
  build:
    commands:
      - pnpm nx build wordly-spa

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: 'dist/apps/wordly-spa/'
